name: GrimVPN Whitelist Collector

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch, Filter, Verify Connections & Build Config
        run: |
          cat << 'EOF' > config.txt
          #profile-title: GrimVPN WL
          #profile-update-interval: 12
          #announce: BEST CONFIG | WHITE LIST
          #support-url: https://t.me/GrimVpnBot
          #profile-web-page-url: https://grimvpn.github.io/
          #hide-settings: 0

          EOF

          {
            curl -sSL "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt"
            echo ""
            curl -sSL "https://raw.githubusercontent.com/zieng2/wl/refs/heads/main/vless_lite.txt"
            echo ""
            curl -sSL "https://raw.githubusercontent.com/zieng2/wl/refs/heads/main/vless_universal.txt"
            echo ""
          } | sed 's/\r$//' | grep -vE '^\s*#|^\s*$' | sort -u > temp_connections.txt

          python3 -c '
          import re
          import socket
          from concurrent.futures import ThreadPoolExecutor

          pattern = re.compile(r"@([^:/?#\s]+):([0-9]+)")

          def check_node(line):
              line = line.strip()
              if not line:
                  return None
              match = pattern.search(line)
              if match:
                  host = match.group(1)
                  port = int(match.group(2))
                  try:
                      with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                          sock.settimeout(2.5)
                          if sock.connect_ex((host, port)) == 0:
                              return line
                  except Exception:
                      pass
                  return None
              return line

          with open("temp_connections.txt", "r") as f:
              lines = f.readlines()

          with ThreadPoolExecutor(max_workers=30) as executor:
              results = executor.map(check_node, lines)

          with open("config.txt", "a") as out_f:
              for res in results:
                  if res:
                      out_f.write(res + "\n")
          '

          rm temp_connections.txt

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add config.txt
          
          if git diff-index --quiet HEAD; then
            echo "Все серверы стабильны, изменений нет. Коммит отменён."
          else
            git commit -m "Auto-update: База обновлена."
            git push
          fi
